spring.application.name=smartcar
spring.datasource.url=jdbc:mysql://localhost:3306/smartcar
spring.datasource.username=${SEU_USUARIO}
spring.datasource.password=${SUA_SENHA}

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
api.ia.key=${API_KEY}



jwt.expiration=86400000
jwt.key=${JWT_KEY:smartcar-secret-key-me-da-10-george}